<?php /* Groups Engine - HTML Contact Report */
	require_once 'report_header.php';

	function nl2p($text) {
		return "<p>" . str_replace("\n", "</p><p>", $text) . "</p>";
	}
	
	if ( current_user_can( 'edit_posts' ) ) { 

		
		if ( $_POST ) {
			global $wpdb;

			$enmge_contact_date = strip_tags($_POST['enmge_contactrange']);
			$enmge_contact_options = strip_tags($_POST['enmge_contactoptions']);

			if ( $enmge_contact_options == '0' ) {
				$enmge_preparredsql = "SELECT * FROM " . $wpdb->prefix . "ge_contacts WHERE (contact_date >= %s OR contact_last_update_day >= %s) ORDER BY contact_date DESC";
				$enmge_findthecontacts = $wpdb->prepare( $enmge_preparredsql, $enmge_contact_date, $enmge_contact_date ); 	
				$enmge_contacts = $wpdb->get_results( $enmge_findthecontacts );
				$enmge_ccount = $wpdb->num_rows;
			} else {
				$enmge_preparredsql = "SELECT * FROM " . $wpdb->prefix . "ge_contacts WHERE (contact_date >= %s OR contact_last_update_day >= %s) AND contact_status = %s ORDER BY contact_date DESC";
				$enmge_findthecontacts = $wpdb->prepare( $enmge_preparredsql, $enmge_contact_date, $enmge_contact_date, $enmge_contact_options ); 	
				$enmge_contacts = $wpdb->get_results( $enmge_findthecontacts );
				$enmge_ccount = $wpdb->num_rows;
			}
			

			$enmge_preparredsqln = "SELECT * FROM " . $wpdb->prefix . "ge_contact_notes ORDER BY contact_note_date DESC"; 	
			$enmge_notes = $wpdb->get_results( $enmge_preparredsqln );
		}
	
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>Groups Engine - Contact Report</title>
	<link rel="stylesheet" href="../../../css/ge_backend.css" type="text/css" />
</head>
<body id="ge-report">

<p class="reportcount"><em><?php echo $enmge_ccount; ?> Contacts Found</em></p>
<h1>Contact Report</h1>

<?php foreach ($enmge_contacts as $contact) { ?>
<div class="contact">
	<h3><?php echo stripslashes($contact->contact_name); ?></span></h3>
	<h5>on <?php echo date('F j, Y', strtotime($contact->contact_date)) ?> at <?php echo date('g:i A', strtotime($contact->contact_date)) ?></h5>
	
	<table id="contactreporttable" cellpadding="0" cellspacing="0">
		<tr>
			<th>Status</th>
			<th><?php echo stripslashes($enmge_grouptitle); ?></th>
			<th>Email</th>
			<th>Phone</th>
			<th>Last Updated By</th>
		</tr>
		<tr>
			<td><?php echo stripslashes($contact->contact_status); ?></td>
			<td><?php echo stripslashes($contact->contact_group_title); ?></td>
			<td><a href="mailto:<?php echo stripslashes($contact->contact_email); ?>"><?php echo $contact->contact_email; ?></a></td>
			<td><?php echo stripslashes($contact->contact_phone); ?></td>
			<td><?php echo stripslashes($contact->contact_last_update); ?></td>
		</tr>
	</table>

	<h4>Message:</h4>
	<div class="contactmessage"><?php echo nl2p('&quot;' . stripslashes($contact->contact_message) . '&quot;') ?></div>

	<?php $enmge_notecount = 1;
	foreach ($enmge_notes as $note) { ?>
		<?php if ($note->contact_id == $contact->contact_id) { ?>
			<?php if ($enmge_notecount == 1) {echo '<h4>Notes:</h4><div class="notesarea">';} $enmge_notecount = $enmge_notecount + 1; ?>
			<h5><strong><?php echo stripslashes($note->contact_note_user); ?></strong> on <?php echo date('F j', strtotime($note->contact_note_date)) ?> at <?php echo date('g:i A', strtotime($note->contact_note_date)) ?>:</h5>
			<?php echo nl2p(stripslashes('&quot;' . $note->contact_note . '&quot;')) ?>
		<?php } ?>
	<?php } ?>
	<?php if ( !empty($enmge_notes) ) {echo '</div>';} ?>
</div>
<?php } ?>


<h5 class="footer">Report generated by <strong>Groups Engine</strong> for <em><?php echo $enmge_options['ministryname']; ?></em> on <?php echo date('F j, Y'); ?></h5>
</body>
</html>
<?php } else {
	$enmge_redirecturl = home_url();
	header("Location: $enmge_redirecturl");
} ?>